<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net48</TargetFrameworks>
    <ImplicitUsings Condition="'$(TargetFramework)' == 'net8.0'">enable</ImplicitUsings>
    <ImplicitUsings Condition="'$(TargetFramework)' == 'net48'">disable</ImplicitUsings>
    <Nullable Condition="'$(TargetFramework)' == 'net8.0'">enable</Nullable>
    <Nullable Condition="'$(TargetFramework)' == 'net48'">disable</Nullable>
    <LangVersion Condition="'$(TargetFramework)' == 'net48'">8.0</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>PSCCMClient.Core</PackageId>
    <VersionPrefix>1.0.0</VersionPrefix>
    <VersionSuffix Condition="'$(GITHUB_RUN_NUMBER)' != ''">dev-$(GITHUB_RUN_NUMBER)</VersionSuffix>
    <Version Condition="'$(VersionSuffix)' == ''">$(VersionPrefix)</Version>
    <Version Condition="'$(VersionSuffix)' != ''">$(VersionPrefix)-$(VersionSuffix)</Version>
    <Authors>Cody Mathis</Authors>
    <Company>PSCCMClient</Company>
    <Description>C# library for interacting with Microsoft Endpoint Configuration Manager (MEMCM) clients</Description>
    <PackageTags>SCCM;MEMCM;ConfigMgr;SystemCenter</PackageTags>
    <RepositoryUrl>https://github.com/CodyMathis123/PSCCMClient</RepositoryUrl>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="Microsoft.Management.Infrastructure" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="System.Management" Version="7.0.2" />
    <PackageReference Include="Microsoft.Management.Infrastructure" Version="2.0.0" />
  </ItemGroup>

</Project>